NAME: "SegNet_VGG"

SEED: 0

DATA:
  ROOT: "/home/caichengjie/anaconda3/envs/torch1.10/daima/BANA-main/data/VOCdevkit/VOC2012"
  MODE: "val"
  PSEUDO_LABEL_FOLDER: ["Generation/Y_crf_u0",
                        "Generation/Y_ret",
#                        "BgMaskfromBoxes",
                        #"Generation/Y_qian"
                        ]#"Generation/Y_crf_u0", "Generation/Y_ret"
  BATCH_SIZE: 8 # Change according to val or train mode, wode shi 8
  CROP_SIZE: (256, 256) #(321, 321)
  NUM_CLASSES: 2

MODEL:
  WEIGHTS: "vgg_caffe.pth" # From PyCaffe and VGG-16 ImageNet pretrained weights
  FREEZE_BN: False
  LAMBDA: 0.1
  DAMP: 7
  DCRF: [4, 121, 5, 3, 3] # DeepLab-V1-LargFOV [bi_w, bi_xy_std, bi_rgb_std, pos_w, pos_xy_std, max_iter]
  LOSS: "CE_CRF" #"NAL", CE_CRF, consistency loss

SOLVER:
  LR: 1e-3
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-4
  MAX_ITER: 23805 #23805
  GAMMA: 0.9
  STEP_SIZE: 10.0
  MILESTONES: [5000]

WANDB:
  MODE: True
  PROJECT: "BANA"
  RESTORE_NAME: "stage3 Run_new" #2 Set a unique run id for your experiment
  CHECKPOINT: "23805.pth"

